function Hd = untitled
%UNTITLED Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 12-May-2019 19:27:02

% FIR least-squares Bandpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 105;  % Sampling Frequency

N      = 1000;  % Order
Fstop1 = 0.2;   % First Stopband Frequency
Fpass1 = 0.5;   % First Passband Frequency
Fpass2 = 5;     % Second Passband Frequency
Fstop2 = 5.5;   % Second Stopband Frequency
Wstop1 = 20;    % First Stopband Weight
Wpass  = 1;     % Passband Weight
Wstop2 = 20;    % Second Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2]);
Hd = dfilt.dffir(b);

% [EOF]
